### ISSUE TITLE
Advice to build a dictionary of already sorted keys

### ISSUE THREAD

**Issue by rickbeeloo** [KeyviDev/keyvi#205]
I have looked through the documentation and issues and it looks like `keyvi` itself sorts the data, for example when I read https://github.com/KeyviDev/keyvi/issues/181. In my case I have two `numpy` arrays, one with 5 billion keys and the another one with the corresponding values. We can sort our 5 billion keys in around 30 minutes using `argsort`. Therefore I wonder what would be the quickest way to build the `keyvi` dictionary from this? Does `keyvi` for example already notice the data is sorted (and does not have to check this again)?

**Comment by hendrikmuhs** [comment]
Sorting is an important part of the construction of the finite state machine, so yes keyvi sorts the data and has used TPIE upfront but switched now to `std::sort` and `boost::sort` (parallel sort). Keyvi does not check whether data is sorted upfront. 

Sorting algorithms usually run quicker if data is already sorted, the more interesting boost sort is explained here: https://www.boost.org/doc/libs/1_67_0/libs/sort/doc/html/sort/parallel.html. Keyvi uses `block_indirect_sort`, according to the docs its `O(n)`.

Detecting sorting is an interesting idea however sort can be locale dependent, I am not sure if `argsort` == `keyvi sort` (equal to using locale `C` when using unix sort). So sorting upfront only works if it can guarantee the "right" sorting.

I would benchmark it:

- presorted vs. unsorted (it might be faster to sort in keyvi, just because items are smaller in keyvi, but `numpy` sorts python objects)
- different memory settings in keyvi, keyvi works for data sizes bigger than the available machine memory, the requirement for sorting is being able to sort super large data sets in an efficient way and overflowing to disk as needed. Therefore keyvi chunks the data, it respects the memory limit you give it. If you are able to give keyvi more memory, it will chunk less an run faster. I might be wrong but `numpy` works completely in memory, does it? I think playing with these settings might have a big impact, I guess your use case uses a large machine, giving keyvi more memory will not only let it run quicker but might result in better compression, too.

Having that said, keyvi has the concept of the [`generator`](https://github.com/KeyviDev/keyvi/blob/master/python/src/pxds/generator.pxd), this is the part that constructs the FST from sorted data. It's only exposed for key-only dictionaries. If your measurements show its worth it, we can expose other generators. However, in the measurements that we did, the bottlenecks were always elsewhere.

**Comment by rickbeeloo** [comment]
Hey @hendrikmuhs  thank you so much for the quick response! I'm going to look at this in more detail :)

> numpy works completely in memory, does it?

Exactly, this currently is not a big problem for us as we have `1.5TB` RAM available, however ideally, as you said, it would be great to make this code work on smaller machines too!

I just create an array with "only" 10 million items and tried to create a keyvi from it, however, the compilation step is already running for like 30 minutes. Am I doing something wrong here? 

```
import numpy as np
import lmdb
from keyvi.compiler import IntDictionaryCompiler, IntDictionaryMerger
import time
from tqdm import tqdm

# Generate data array
np.random.seed(1)
arr = np.arange(10000000)

# Keyvi
print('Setup')
dictionary_compiler = IntDictionaryCompiler({"memory_limit_mb": "100000"}) #100gb

# Insert
print('Inserting')
for key in tqdm(arr, total = arr.size ):
    dictionary_compiler.Add(str(key), int(key))  # int(key) would also be fine but this raised an error
    
# Compile
print('Compiling')
start = time.time()
dictionary_compiler.Compile()
dictionary_compiler.WriteToFile('kevi.dict')
print('Compiling took {}'.format(time.time() - start))  
```

**Comment by hendrikmuhs** [comment]
Do I get this right, you insert a counter from 1 to 10 million? Does your real data look like this, too?

This is not a good use of keyvi, keyvi exploits repetition on both the key as well as the value space. It won't work well for fully unique or truely random data.

I will look into it in more detail later, 10 million shouldn't be a problem. Are you running on slow disks maybe?

**Comment by hendrikmuhs** [comment]
Your example code - except the 100GB limit, I don't have such a machine - takes 25 seconds for me on my 5 year old laptop. There is something wrong in your setup. Can you test without the 100GB memory limit? Is this a cloud machine? network attached ebs storage might slow it down.

**Comment by rickbeeloo** [comment]
Indeed, when I remove the `limit = 100GB` it runs in 7 seconds. Is that something related to keyvi or our server? (we use local machines, not cloud based servers)

**Comment by hendrikmuhs** [comment]
Thanks! This sound like a bug to me. We have been using keyvi at large scale, but not on machines of that size. I guess there is some magic boundary.

Did `limit = 100GB` finish at all? Or did this trigger an endless loop?
I will try to reproduce with some larger values on another machine, but I don't have access to machines of similar size.

I still think you can/should increase the memory limit, but maybe you start simple with the defaults and than experiment with larger values step by step. 

If you have time and resources to find out when it starts to run slow / loop forever, this information would be awesome.

**Comment by rickbeeloo** [comment]
I will run it tonight, the Netherlands here :), with `limit = 100GB` and check if it ever finishes. I Will let you know in the morning!

**Comment by rickbeeloo** [comment]
It indeed was still running in the morning. Perhaps I can gradually increase the memory limit, as you suggested, and see where the turning point is on our machine

**Comment by rickbeeloo** [comment]
@hendrikmuhs , not really related to this but I wonder whether we can get all the keys for a given dictionary?

**Comment by hendrikmuhs** [comment]
Thanks, this sound indeed like an infinite loop. I guess due to some numeric overflow. A brief look at the code already revealed a candidate.

As for getting all keys, the python, there are 3 methods on a dict: 

```
 'GetAllItems',
 'GetAllKeys',
 'GetAllValues',
```

**Comment by rickbeeloo** [comment]
Let me know when I can help by checking keyvi on our machine!

**Comment by narekgharibyan** [comment]
I thought to spend some time on this and was doing a binary search to find the turning point for memory limit.
Turns out that it's `99271`.


My laptop has a `32GB` of RAM, and if I use this line:
```
dictionary_compiler = IntDictionaryCompiler({"memory_limit_mb": "99271"})  # 100gb
```
It compiles the dict under 4 seconds. 

But if I increase the limit by just 1 MB.
```
dictionary_compiler = IntDictionaryCompiler({"memory_limit_mb": "99272"})  # 100gb
```
It seems to never finish.


Moreover I can observe similar behavior even with `100000` keys.
```
arr = np.arange(100000)
```
but not with `10000`.

```
arr = np.arange(10000)
```

@hendrikmuhs seems you have started looking into this, so I didn't run debugger and dig into the code, but let me know if you need a hand on this.

**Comment by narekgharibyan** [comment]
Update: 

The run with `100k` keys.
```
arr = np.arange(100000)
```
and with memory limit of `99272 MB` finished after 424 seconds.

But if I set memory limit to `99271 MB` it finishes under 0.13 seconds.

**Comment by hendrikmuhs** [comment]
My investigation so far, it seems to be this method:

https://github.com/KeyviDev/keyvi/blob/master/keyvi/include/keyvi/dictionary/fsa/internal/minimization_hash.h#L85

For high numbers, like the the 100GB it suddenly starts returning `0` for both parameter it is supposed to produce. This makes the compiler run crazy and re-allocate for every state (every character).

What does this do: It tries to find a good configuration for using the given memory budget. This memory is used for minimization. Minimization == compression == finding duplicate subtrees in the constructed FST. This is done by using a stack of hash tables. 

Poor design, this helper method deserves some love.

**Comment by hendrikmuhs** [comment]
@rickbeeloo Thanks again for the bug report. I think #206 fixes the issue.

If you need further assistance, do not hesitate to ask. You can also use https://github.com/KeyviDev/keyvi/discussions which might be the better platform for discussions like this.

Back to the root: Have you already benchmarked using numpy's sort vs. keyvi's builtin sort?

**Comment by hendrikmuhs** [comment]
and FWIW I will create a release package as soon as I find time.
