### ISSUE TITLE
Allow integer list as a key

### ISSUE THREAD

**Issue by vsraptor** [KeyviDev/keyvi#225]
**Is your feature request related to a problem? Please describe.**

It will allow to store arbitrary data/sequences not just text

**Describe the solution you'd like**

Ability to use list of INTEGER's as a key f.e.:

index.Set([5,77,89,999], "24.9")

if my understanding  is correct that the key is FSM-like then utf-8 characters are special case of number list with numbers of 0 .. 255

**Describe alternatives you've considered**

from outside may be u can have code to convert/encode numbers to characters, but it will be slower and cumbersome ... keyvi idea is that its fast isnt it ;)

**Additional context**

**Comment by hendrikmuhs** [comment]
It's possible to index a bytes instead of string, so you should be able to index lists of integers already, if you encode them as bytes. If you index values > 256 you need to choose little endian, big endian or you use variable length integers. I think tooling is available in python and I think this should be reasonable fast. Longer term, I agree, it would be nice if it's built-in.

**Comment by vsraptor** [comment]
kewl ;) ihope you add it in the future
