### ISSUE TITLE
Refactor StringValueStore to use external memory to limit memory usage.

### ISSUE THREAD

**Issue by narekgharibyan** [KeyviDev/keyvi#69]
`JsonValueStore` already has this functionality implemented. Probably it's possible to factor out common code and reuse it in both value stores.

**Comment by hendrikmuhs** [comment]
An option I see is using template specialization (or class inheritance?): The `StringValueStore` and the `JsonValueStore` should only differ by 2 operations: encoding and decoding json, everything else should be almost identical.

**Comment by narekgharibyan** [comment]
To me it sounds like a good application for inheritance, but @amit-cliqz is going to investigate this on upcoming days.

**Comment by hendrikmuhs** [comment]
While working on #93, I realized that the `StringValueStore` is quite different to the `JsonValueStore`, so reusage is more complicated. #93 is a step forward, it reuses parts and makes use of external memory. 

**Some background:**

The `JsonValueStore` has been based on `StringValueStore` but later been completely rewritten to support compression. As this has been an breaking change `JsonValueStore` got renamed to `JsonValueStoreDeprecated` and the new `JsonValueStore` took it's place using a new enum value. For a while both existed while `JsonValueStoreDeprecated` got faded out and finally removed somewhen in 0.1 days, only the enum is still there.

I would actually do the same for `StringValueStore` in order to support compression, this *new* `StringValueStore` will - as discussed - share code with `JsonValueStore`. The old `StringValueStore` will be renamed and removed over time.

**Comment by narekgharibyan** [comment]
As #93 also implements the functionality this issue requires, I'd suggest to close this one with #93 merge, and later on open a new issue to "add a compression functionality and make use of common code".

**Comment by hendrikmuhs** [comment]
fixed by #93
